<?php
/**
 * CodeForge-Engine Developer CLI Tool
 * Usage: 
 *   php forge make:controller <ControllerName>
 *   php forge make:model <ModelName> [--table=<tableName>]
 *   php forge make:migration <MigrationName>
 *   php forge migrate
 */

// Define console colors
define('COLOR_SUCCESS', "\033[32m");
define('COLOR_INFO', "\033[36m");
define('COLOR_WARNING', "\033[33m");
define('COLOR_ERROR', "\033[31m");
define('COLOR_RESET', "\033[0m");
define('COLOR_BOLD', "\033[1m");

// Ensure running via CLI
if (php_sapi_name() !== 'cli') {
    die("This script can only be run from the command line.");
}

// Load framework bootstrap
require_once __DIR__ . '/core/App.php';
$app = \Forge\Core\App::getInstance();

function logConsole($type, $msg) {
    $color = '';
    $prefix = '';
    switch ($type) {
        case 'success':
            $color = COLOR_SUCCESS;
            $prefix = '✔ SUCCESS: ';
            break;
        case 'info':
            $color = COLOR_INFO;
            $prefix = 'ℹ INFO: ';
            break;
        case 'warning':
            $color = COLOR_WARNING;
            $prefix = '⚠ WARNING: ';
            break;
        case 'error':
            $color = COLOR_ERROR;
            $prefix = '✖ ERROR: ';
            break;
        default:
            $color = COLOR_RESET;
            break;
    }
    echo $color . $prefix . $msg . COLOR_RESET . PHP_EOL;
}

$args = $argv;
array_shift($args); // Remove script name

if (empty($args) || in_array('--help', $args) || in_array('-h', $args)) {
    showDeveloperHelp();
    exit;
}

$command = array_shift($args);

switch ($command) {
    case 'make:controller':
        handleMakeController($args);
        break;
    case 'make:model':
        handleMakeModel($args);
        break;
    case 'make:migration':
        handleMakeMigration($args);
        break;
    case 'migrate':
        handleMigrate($app);
        break;
    default:
        logConsole('error', "Unknown command '{$command}'.");
        showDeveloperHelp();
        exit(1);
}

// =<ctrl42>= COMMAND HANDLERS =t=

function handleMakeController($args) {
    if (empty($args)) {
        logConsole('error', "Missing controller name. Usage: php forge make:controller <Name>");
        exit(1);
    }
    
    $name = $args[0];
    if (strpos($name, 'Controller') === false) {
        $name .= 'Controller';
    }
    
    $targetFile = __DIR__ . '/app/Controllers/' . $name . '.php';
    
    if (file_exists($targetFile)) {
        logConsole('warning', "Controller '{$name}' already exists at: {$targetFile}");
        exit(1);
    }
    
    $dir = dirname($targetFile);
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    
    $template = <<<PHP
<?php
namespace App\Controllers;

use Forge\Core\Controller;

/**
 * {$name} - Generated by CodeForge CLI
 */
class {$name} extends Controller {
    
    public function index() {
        // Return dynamic views or json responses
        return \$this->json(['message' => 'Hello from {$name}']);
    }
}
PHP;

    if (file_put_contents($targetFile, $template) !== false) {
        logConsole('success', "Scaffolded Controller: {$name} ➜ app/Controllers/{$name}.php");
    } else {
        logConsole('error', "Failed writing to: {$targetFile}");
    }
}

function handleMakeModel($args) {
    if (empty($args)) {
        logConsole('error', "Missing model name. Usage: php forge make:model <Name>");
        exit(1);
    }
    
    $name = $args[0];
    
    // Parse table option
    $table = null;
    foreach ($args as $arg) {
        if (strpos($arg, '--table=') === 0) {
            $table = substr($arg, 8);
        }
    }
    
    $targetFile = __DIR__ . '/app/Models/' . $name . '.php';
    
    if (file_exists($targetFile)) {
        logConsole('warning', "Model '{$name}' already exists at: {$targetFile}");
        exit(1);
    }
    
    $dir = dirname($targetFile);
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    
    $tableProperty = '';
    if ($table) {
        $tableProperty = "    protected static \$table = '{$table}';\n";
    }
    
    $template = <<<PHP
<?php
namespace App\Models;

use Forge\Core\Model;

/**
 * {$name} Model - Generated by CodeForge CLI
 */
class {$name} extends Model {
{$tableProperty}}
PHP;

    if (file_put_contents($targetFile, $template) !== false) {
        logConsole('success', "Scaffolded Model: {$name} ➜ app/Models/{$name}.php");
    } else {
        logConsole('error', "Failed writing to: {$targetFile}");
    }
}

function handleMakeMigration($args) {
    if (empty($args)) {
        logConsole('error', "Missing migration name. Usage: php forge make:migration <Name>");
        exit(1);
    }
    
    $name = strtolower(preg_replace('/(?<!^)[A-Z]/', '_$0', $args[0]));
    $timestamp = time();
    $filename = "m_{$timestamp}_{$name}.php";
    
    $targetFile = __DIR__ . '/database/migrations/' . $filename;
    
    $dir = dirname($targetFile);
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    
    $template = <<<PHP
<?php
/**
 * Migration: {$args[0]}
 */
return new class {
    
    public function up(\$db) {
        // Write raw query commands e.g.:
        // \$db->query("CREATE TABLE test (id INT AUTO_INCREMENT PRIMARY KEY)");
    }
    
    public function down(\$db) {
        // Write rollback logic e.g.:
        // \$db->query("DROP TABLE IF EXISTS test");
    }
};
PHP;

    if (file_put_contents($targetFile, $template) !== false) {
        logConsole('success', "Scaffolded Migration: {$filename} ➜ database/migrations/{$filename}");
    } else {
        logConsole('error', "Failed writing to: {$targetFile}");
    }
}

function handleMigrate($app) {
    try {
        $db = $app->get('database');
    } catch (\Exception $e) {
        logConsole('error', "Database connection failed. Migration cancelled.");
        logConsole('error', $e->getMessage());
        exit(1);
    }
    
    // Create migrations log table if not exists
    $db->query("
        CREATE TABLE IF NOT EXISTS `migrations` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `migration` VARCHAR(255) UNIQUE NOT NULL,
            `batch` INT NOT NULL,
            `migrated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");
    
    // Read executed migrations
    $executedRaw = $db->table('migrations')->get();
    $executed = array_column($executedRaw, 'migration');
    
    // Find next batch number
    $maxBatch = $db->table('migrations')->select('MAX(batch) as max_batch')->first()['max_batch'] ?? 0;
    $nextBatch = $maxBatch + 1;
    
    // Scan migrations folder
    $migrationsDir = __DIR__ . '/database/migrations';
    if (!is_dir($migrationsDir)) {
        logConsole('info', "No migrations directory found. Run make:migration to create one.");
        exit;
    }
    
    $files = scandir($migrationsDir);
    $migrationFiles = array_filter($files, function($file) use ($migrationsDir) {
        return is_file($migrationsDir . '/' . $file) && pathinfo($file, PATHINFO_EXTENSION) === 'php';
    });
    
    sort($migrationFiles); // Ensure ordered execution
    
    $runCount = 0;
    foreach ($migrationFiles as $file) {
        if (in_array($file, $executed)) {
            continue; // Skip already executed migrations
        }
        
        logConsole('info', "Migrating: {$file}");
        
        // Load closure template migration class
        $migrationObj = include $migrationsDir . '/' . $file;
        
        try {
            // Execute down / up operations
            $migrationObj->up($db);
            
            // Log to migration table
            $db->table('migrations')->insert([
                'migration' => $file,
                'batch' => $nextBatch
            ]);
            
            logConsole('success', "Migrated:  {$file}");
            $runCount++;
        } catch (\Exception $e) {
            logConsole('error', "Migration Failed on: {$file}");
            logConsole('error', $e->getMessage());
            exit(1);
        }
    }
    
    if ($runCount === 0) {
        logConsole('info', "Nothing to migrate. Database is up to date.");
    } else {
        logConsole('success', "Completed running {$runCount} migrations in batch #{$nextBatch}!");
    }
}

function showDeveloperHelp() {
    echo COLOR_BOLD . "CodeForge-Engine Developer CLI" . COLOR_RESET . PHP_EOL;
    echo "==================================" . PHP_EOL;
    echo "Developer scaffolding assistant and database version manager." . PHP_EOL . PHP_EOL;
    echo COLOR_BOLD . "Usage:" . COLOR_RESET . PHP_EOL;
    echo "  php forge <command> [arguments] [options]" . PHP_EOL . PHP_EOL;
    echo COLOR_BOLD . "Commands:" . COLOR_RESET . PHP_EOL;
    echo "  make:controller <Name>       Scaffold new view/api controller" . PHP_EOL;
    echo "  make:model <Name> [--table]  Scaffold new ActiveRecord model class" . PHP_EOL;
    echo "  make:migration <Name>        Scaffold new database migration file" . PHP_EOL;
    echo "  migrate                      Run all outstanding database migrations" . PHP_EOL;
}
